site_name: PDF‑OCR‑Pipeline
## site_url removed for portability; default will be used
# site_url: https://your‑site.example.com
repo_url: https://github.com/yourorg/pdf‑ocr‑pipeline
theme:
  name: material

docs_dir: docs

nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - Usage Guide: usage_guide.md
  - API Reference:
      - Overview: api.md
      - Generated Reference: api/index.md
  - Project Organisation: project_organization.md
  - Troubleshooting: troubleshooting.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_signature_annotations: true
            docstring_style: google

markdown_extensions:
  - admonition
  - toc:
      permalink: true
